import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased dark`}>
        <div className='flex flex-col h-screen'>
          <Navbar />
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  )
}
